.Dd __DATE__
.Dt dsdump 1
.Os Darwin
.Sh NAME
.Nm dsdump
.Nd An improved nm + objc/swift class-dump
.Sh SYNOPSIS
.Nm
.Ar subcommand Op Ar option ... Ar filename
.Sh DESCRIPTION
.Nm dsdump
Provides an "nm-improved" experience when working with Mach-O executables
and can display
.Nm C, Objective-C,
and
.Nm Swift
information
.Sh SUBCOMMANDS
.Sh SEE ALSO 
.Xr nm 1 ,
.Xr objdump 1 ,
.Xr vmmap 1
