# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget LLVMTestingSupport FileCheck llvm-PerfectShuffle count not yaml-bench lli-child-target gtest gtest_main)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target LLVMTestingSupport
add_library(LLVMTestingSupport STATIC IMPORTED)

set_target_properties(LLVMTestingSupport PROPERTIES
  INTERFACE_LINK_LIBRARIES "LLVMSupport;\$<LINK_ONLY:gtest>"
)

# Create imported target FileCheck
add_executable(FileCheck IMPORTED)

# Create imported target llvm-PerfectShuffle
add_executable(llvm-PerfectShuffle IMPORTED)

# Create imported target count
add_executable(count IMPORTED)

# Create imported target not
add_executable(not IMPORTED)

# Create imported target yaml-bench
add_executable(yaml-bench IMPORTED)

# Create imported target lli-child-target
add_executable(lli-child-target IMPORTED)

# Create imported target gtest
add_library(gtest STATIC IMPORTED)

set_target_properties(gtest PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;LLVMSupport"
)

# Create imported target gtest_main
add_library(gtest_main STATIC IMPORTED)

set_target_properties(gtest_main PROPERTIES
  INTERFACE_LINK_LIBRARIES "gtest;LLVMSupport"
)

# Import target "LLVMTestingSupport" for configuration "Debug"
set_property(TARGET LLVMTestingSupport APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(LLVMTestingSupport PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/lolgrep/code/xref/lib/libLLVMTestingSupport.a"
  )

# Import target "FileCheck" for configuration "Debug"
set_property(TARGET FileCheck APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(FileCheck PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/lolgrep/code/xref/bin/FileCheck"
  )

# Import target "llvm-PerfectShuffle" for configuration "Debug"
set_property(TARGET llvm-PerfectShuffle APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(llvm-PerfectShuffle PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/lolgrep/code/xref/bin/llvm-PerfectShuffle"
  )

# Import target "count" for configuration "Debug"
set_property(TARGET count APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(count PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/lolgrep/code/xref/bin/count"
  )

# Import target "not" for configuration "Debug"
set_property(TARGET not APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(not PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/lolgrep/code/xref/bin/not"
  )

# Import target "yaml-bench" for configuration "Debug"
set_property(TARGET yaml-bench APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(yaml-bench PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/lolgrep/code/xref/bin/yaml-bench"
  )

# Import target "lli-child-target" for configuration "Debug"
set_property(TARGET lli-child-target APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(lli-child-target PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/lolgrep/code/xref/bin/lli-child-target"
  )

# Import target "gtest" for configuration "Debug"
set_property(TARGET gtest APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gtest PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/lolgrep/code/xref/lib/libgtest.a"
  )

# Import target "gtest_main" for configuration "Debug"
set_property(TARGET gtest_main APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(gtest_main PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/lolgrep/code/xref/lib/libgtest_main.a"
  )

# Make sure the targets which have been exported in some other 
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "LLVMSupport" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
